# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200103_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='job_title',
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default=('job_title', 'one'), max_length=200),
            preserve_default=False,
        ),
    ]
